const STATUS = {
  SUCCESS: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  SERVER_ERROR: 500,
};


const ROLES = {
  ADMIN: "ADMIN",
  USER: "USER",
  CONETENT_CONTRIBUTOR: "CONTENT_CONTRIBUTOR",
  REFUGEE: "REFUGEE",
};

const ORGANIZATION_TYPES = {
  NGO: "NGO",
  GOVERNMENT: "GOVERNMENT",
  PRIVATE: "PRIVATE",
  INTERNATIONAL: "INTERNATIONAL",
};

const ACESS_LEVELS = {
  SUPER: "SUPER",
  STANDARD: "STANDARD",
};

export {STATUS , ROLES, ORGANIZATION_TYPES, ACESS_LEVELS};